[project]
name = "PyFracVAL"
version = "0.0.1"
description = "Python implementation of FracVAL for generting fractal particle clusters"
readme = "README.md"
authors = [
  { name = "aetherspritee" },
  { name = "Mirza Arnaut", email = "mirza.arnaut@tu-dortmund.de" },
]
requires-python = ">=3.10,<3.13"
dependencies = [
    "numba>=0.60.0",
    "numpy>=1.26.4,<2.0.0",
    "pyvista>=0.44.1",
    "scipy>=1.14.1",
]
