name: "Build docs"
on:
  workflow_dispatch:
  push:
    paths:
      - "docs/**/*"
      - ".github/workflows/docs.yml"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v5
      - run: pip install --group docs
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
